/**
 * GetSponsorRoi DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetSponsorRoiReportParams } from "@denselink/core/reports";

export function createGetSponsorRoiRequest(overrides: Partial<GetSponsorRoiReportParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
