/**
 * Piggyback DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: density
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Piggyback DTOs
 *
 * DDD: Application DTOs for Piggyback use cases.
 */

import type { ListPiggybackRegionsParams } from "@denselink/core/density/types";

export type ListPiggybackRegionsInput = ListPiggybackRegionsParams;

export type ListPiggybackRegionsOutput = {};
