/**
 * ExecuteGetVenueProgramme - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetVenueProgramme Use Case
 *
 * DDD: Application use case for get Venue.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetVenueProgrammeInput, GetVenueProgrammeOutput } from "../dto/venue.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { VenueRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetVenueProgramme {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly venue: VenueRepository
  ) {}

  async execute(input: GetVenueProgrammeInput): Promise<GetVenueProgrammeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.venId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).venueProgrammeId) {
      throw new ValidationError("venueProgrammeId is required");
    }
    const venueprogrammeId = (input as any).venueProgrammeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.venue.getVenueProgramme({ venueProgrammeId: venueprogrammeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${venueprogrammeId}`);
    }

    return entity as GetVenueProgrammeOutput;
  }
}
