/**
 * ExecuteCreateAlwaysOnCampaign - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateAlwaysOnCampaign Use Case
 *
 * DDD: Application use case for create AlwaysOnCampaign.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateAlwaysOnCampaignInput, CreateAlwaysOnCampaignOutput } from "../dto/always-on-campaign.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { AlwaysOnCampaignRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateAlwaysOnCampaign {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly alwaysOnCampaign: AlwaysOnCampaignRepository
  ) {}

  async execute(input: CreateAlwaysOnCampaignInput): Promise<CreateAlwaysOnCampaignOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.venId();

    // All field names extracted from OpenAPI spec: enabled, name, venueProgrammeId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (venues domain)
    const entityId = this.idGenerator.venId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.alwaysOnCampaign.createAlwaysOnCampaign({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateAlwaysOnCampaignOutput;
  }
}
