/**
 * Reports DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Reports Domain Module - Composition root
 *
 * DDD: Composition root for reports domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  BetaCohortRepositoryAdapter,
  ContributionRankRepositoryAdapter,
  DensityRepositoryAdapter,
  SponsorRoiRepositoryAdapter,
} from "@denselink/adapters/reports";
import { getIdGeneratorService } from "@denselink/adapters";
import type { AdapterDynamoDBClient } from "@denselink/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetBetaCohort,
  ExecuteGetContributionRank,
  ExecuteGetDensityReport,
  ExecuteGetSponsorRoiReport,
} from "@denselink/services/reports/usecases";
// Ports (interfaces)
import type {
  BetaCohortRepository,
  ContributionRankRepository,
  DensityRepository,
  SponsorRoiRepository,
} from "@denselink/services/reports/ports";

export interface ReportsDomainModule {
  repos: {
    betaCohorts: BetaCohortRepository;
    contributionRanks: ContributionRankRepository;
    densities: DensityRepository;
    sponsorRois: SponsorRoiRepository;
  };
  useCases: {
    betaCohorts: {
      get: ExecuteGetBetaCohort;
    };
    contributionRanks: {
      get: ExecuteGetContributionRank;
    };
    densities: {
      get: ExecuteGetDensityReport;
    };
    sponsorRois: {
      get: ExecuteGetSponsorRoiReport;
    };
  };
}

export function buildReportsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ReportsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      betaCohorts?: BetaCohortRepository;
      contributionRanks?: ContributionRankRepository;
      densities?: DensityRepository;
      sponsorRois?: SponsorRoiRepository;
    } = {};

    obj.betaCohorts = new BetaCohortRepositoryAdapter(dynamoClient);
    obj.contributionRanks = new ContributionRankRepositoryAdapter(dynamoClient);
    obj.densities = new DensityRepositoryAdapter(dynamoClient);
    obj.sponsorRois = new SponsorRoiRepositoryAdapter(dynamoClient);
    return {
      betaCohorts: obj.betaCohorts!,
      contributionRanks: obj.contributionRanks!,
      densities: obj.densities!,
      sponsorRois: obj.sponsorRois!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    betaCohorts: {
      get: new ExecuteGetBetaCohort(executionContext, idGenerator, repos.betaCohorts),
    },
    contributionRanks: {
      get: new ExecuteGetContributionRank(executionContext, idGenerator, repos.contributionRanks),
    },
    densities: {
      get: new ExecuteGetDensityReport(executionContext, idGenerator, repos.densities),
    },
    sponsorRois: {
      get: new ExecuteGetSponsorRoiReport(executionContext, idGenerator, repos.sponsorRois),
    },
  };
  return { repos, useCases: useCases as ReportsDomainModule["useCases"] };
}
