/**
 * Handlers for Aggregate
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TelemetryDomainModule } from "../dependencies/telemetry-ddd.dependencies.js";
import type { IngestNodeTelemetryInput } from "@denselink/services/telemetry";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/telemetry/aggregates
 * Operation: ingestNodeTelemetry
 */
export async function ingestNodeTelemetry(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TelemetryDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: IngestNodeTelemetryInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.aggregates.get.execute(input);
  return reply.code(200).send(result);
}


