/**
 * Routes for AlwaysOnCampaign
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createAlwaysOnCampaign, listAlwaysOnCampaigns } from "../handlers/always-on-campaign.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function alwaysOnCampaignRoutes(fastify: FastifyInstance) {
  // POST /v1/always-on-campaigns (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/always-on-campaigns",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVenuesDependenciesForRequest();
        await createAlwaysOnCampaign(request, reply, deps);
      });
    }
  );


  // GET /v1/always-on-campaigns (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/always-on-campaigns",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVenuesDependenciesForRequest();
        await listAlwaysOnCampaigns(request, reply, deps);
      });
    }
  );


}
