/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { alwaysOnCampaignRoutes } from "./always-on-campaign.routes.js";
export { venueRoutes } from "./venue.routes.js";
