/**
 * Routes for Venue
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createVenueProgramme, getVenueProgramme, listVenueProgrammes } from "../handlers/venue.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function venueRoutes(fastify: FastifyInstance) {
  // POST /v1/venues (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/venues",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVenuesDependenciesForRequest();
        await createVenueProgramme(request, reply, deps);
      });
    }
  );


  // GET /v1/venues (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/venues",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVenuesDependenciesForRequest();
        await listVenueProgrammes(request, reply, deps);
      });
    }
  );


  // GET /v1/venues/{venueProgrammeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/venues/:venueProgrammeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { venueProgrammeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getVenuesDependenciesForRequest();
        await getVenueProgramme(request, reply, deps);
      });
    }
  );


}
