/**
 * Aggregate DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Aggregate DTOs
 *
 * DDD: Application DTOs for Aggregate use cases.
 */

import type { IngestNodeTelemetryRequestInput } from "@denselink/core/telemetry/types";

export type IngestNodeTelemetryInput = IngestNodeTelemetryRequestInput;

export type IngestNodeTelemetryOutput = {};
