/**
 * Meshport Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: meshports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MeshportEntity } from "@denselink/core/meshports/models/index.js";
import { meshportsSchemas } from "@denselink/core/meshports";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mpt";

export function createMeshport(overrides: Partial<MeshportEntity> = {}) {
  const raw = {
    id: overrides.id ?? `mpt_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    appId: overrides.appId ?? `app_${ulid().toLowerCase()}`,
    port: overrides.port ?? faker.number.int(),
    status: overrides.status ?? "allocated",
    ...overrides,
  };

  return meshportsSchemas.MeshPort.parse(raw);
}

export function meshportBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMeshport(overrides));
}
