/**
 * BetaCohort DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BetaCohort DTOs
 *
 * DDD: Application DTOs for BetaCohort use cases.
 */

export type GetBetaCohortInput = {};

export type GetBetaCohortOutput = {};
