/**
 * ExecuteIssueLicenseKey - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteIssueLicenseKey Use Case
 *
 * DDD: Application use case for get License.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { IssueLicenseKeyInput, IssueLicenseKeyOutput } from "../dto/license.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { LicenseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteIssueLicenseKey {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly license: LicenseRepository
  ) {}

  async execute(input: IssueLicenseKeyInput): Promise<IssueLicenseKeyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.licId();

    // All field names extracted from OpenAPI spec: appId, developerId, meshPort, tier
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).appId) {
      throw new ValidationError("appId is required");
    }
    const appId = (input as any).appId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.license.issueLicenseKey({ appId: appId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${appId}`);
    }

    return entity as IssueLicenseKeyOutput;
  }
}
