/**
 * Handlers for Density
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportsDomainModule } from "../dependencies/reports-ddd.dependencies.js";
import type { GetDensityReportInput } from "@denselink/services/reports";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/reports/density
 * Operation: getDensityReport
 */
export async function getDensityReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { city?: string | string[], appId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDensityReportInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.densities.get.execute(input);
  return reply.code(200).send(result);
}


