/**
 * Handlers for SponsorRoi
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ReportsDomainModule } from "../dependencies/reports-ddd.dependencies.js";
import type { GetSponsorRoiReportInput } from "@denselink/services/reports";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/reports/sponsor-roi
 * Operation: getSponsorRoiReport
 */
export async function getSponsorRoiReport(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { venueProgrammeId?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ReportsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSponsorRoiReportInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.sponsorRois.get.execute(input);
  return reply.code(200).send(result);
}


