/**
 * ExecuteGetContributionRank - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetContributionRank Use Case
 *
 * DDD: Application use case for get ContributionRank.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetContributionRankInput, GetContributionRankOutput } from "../dto/contribution-rank.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { ContributionRankRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetContributionRank {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly contributionRank: ContributionRankRepository
  ) {}

  async execute(input: GetContributionRankInput): Promise<GetContributionRankOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.contributionRank.getContributionRank({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetContributionRankOutput;
  }
}
