/**
 * ExecuteGetDensityReport - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetDensityReport Use Case
 *
 * DDD: Application use case for get Density.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetDensityReportInput, GetDensityReportOutput } from "../dto/density.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { DensityRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetDensityReport {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly density: DensityRepository
  ) {}

  async execute(input: GetDensityReportInput): Promise<GetDensityReportOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.density.getDensityReport({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetDensityReportOutput;
  }
}
