/**
 * ExecuteGetBetaCohort - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetBetaCohort Use Case
 *
 * DDD: Application use case for get BetaCohort.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetBetaCohortInput, GetBetaCohortOutput } from "../dto/beta-cohort.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { BetaCohortRepository } from "../ports";
import { NotFoundError } from "../errors";

export class ExecuteGetBetaCohort {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly betaCohort: BetaCohortRepository
  ) {}

  async execute(input: GetBetaCohortInput): Promise<GetBetaCohortOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.rptId();

    // All field names extracted from OpenAPI spec: none
    // Load entity via repository (no ID field - uses input directly, pass correlation ID for response meta)
    const entity = await this.betaCohort.getBetaCohort({ ...input, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found`);
    }

    return entity as GetBetaCohortOutput;
  }
}
