/**
 * ExecuteListMeshPorts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: meshports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMeshPorts Use Case
 *
 * DDD: Application use case for list Meshport.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMeshPortsInput, ListMeshPortsOutput } from "../dto/meshport.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { MeshportRepository } from "../ports";

export class ExecuteListMeshPorts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly meshport: MeshportRepository
  ) {}

  async execute(input: ListMeshPortsInput): Promise<ListMeshPortsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mptId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.meshport.listMeshPorts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMeshPortsOutput;
  }
}
