/**
 * ListGrantMilestones handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listGrantMilestones } from "@denselink/api-server/domains/grants/handlers";
import type { GrantsDDDDependencies } from "@denselink/api-server/domains/grants";
import { createMilestone as createMilestoneEntity } from "@denselink/factories/grants";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@denselink/tests/shared";
import { GRANTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListGrantMilestones", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GrantsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GrantsDDDDependencies>(
      GRANTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createMilestoneEntity({ orgId }),
      createMilestoneEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListGrantMilestones, "execute").mockResolvedValue(useCaseResult);

    await listGrantMilestones(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListGrantMilestones.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
