/**
 * Handlers for Disburse
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GrantsDomainModule } from "../dependencies/grants-ddd.dependencies.js";
import type { DisburseMilestoneInput } from "@denselink/services/grants";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/milestones/{milestoneId}/disburse
 * Operation: disburseMilestone
 */
export async function disburseMilestone(
  request: FastifyRequest<{ Params: { milestoneId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GrantsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DisburseMilestoneInput = {
    milestoneId: request.params.milestoneId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.disburses.get.execute(input);
  return reply.code(200).send(result);
}


