/**
 * Routes for Meshport
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: meshports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { allocateMeshPort, getMeshPort, listMeshPorts, revokeMeshPort } from "../handlers/meshport.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function meshportRoutes(fastify: FastifyInstance) {
  // POST /v1/meshports (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/meshports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMeshportsDependenciesForRequest();
        await allocateMeshPort(request, reply, deps);
      });
    }
  );


  // GET /v1/meshports (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/meshports",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMeshportsDependenciesForRequest();
        await listMeshPorts(request, reply, deps);
      });
    }
  );


  // GET /v1/meshports/{meshPortId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/meshports/:meshPortId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { meshPortId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMeshportsDependenciesForRequest();
        await getMeshPort(request, reply, deps);
      });
    }
  );


  // DELETE /v1/meshports/{meshPortId} (unscoped; scope set for security middleware)
  fastify.delete(
    "/v1/meshports/:meshPortId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { meshPortId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getMeshportsDependenciesForRequest();
        await revokeMeshPort(request, reply, deps);
      });
    }
  );


}
