/**
 * Meshport DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: meshports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Meshport DTOs
 *
 * DDD: Application DTOs for Meshport use cases.
 */

import type { AllocateMeshPortRequestInput, GetMeshPortParams, ListMeshPortsParams, RevokeMeshPortParams } from "@denselink/core/meshports/types";

export type ListMeshPortsInput = ListMeshPortsParams;

export type AllocateMeshPortInput = AllocateMeshPortRequestInput;

export type GetMeshPortInput = GetMeshPortParams;

export type RevokeMeshPortInput = RevokeMeshPortParams;

export type ListMeshPortsOutput = {};

export type AllocateMeshPortOutput = {};

export type GetMeshPortOutput = {};

export type RevokeMeshPortOutput = {};
