/**
 * MeshportRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: meshports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MeshportRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements MeshportRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  MeshportRepository,
} from "@denselink/services/meshports";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { MeshportRepositoryDdb } from "./meshport-repository.ddb.js";

/**
 * MeshportRepositoryAdapter
 *
 * Implements MeshportRepository port for infrastructure layer.
 */
export class MeshportRepositoryAdapter implements MeshportRepository {
  private readonly ddb: MeshportRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new MeshportRepositoryDdb(this.dynamoClient);
  }

  async listMeshPorts(input: Parameters<MeshportRepository['listMeshPorts']>[0]): Promise<Awaited<ReturnType<MeshportRepository['listMeshPorts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listMeshPorts(input);
  }

  async allocateMeshPort(input: Parameters<MeshportRepository['allocateMeshPort']>[0]): Promise<Awaited<ReturnType<MeshportRepository['allocateMeshPort']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.allocateMeshPort(input);
  }

  async getMeshPort(input: Parameters<MeshportRepository['getMeshPort']>[0]): Promise<Awaited<ReturnType<MeshportRepository['getMeshPort']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getMeshPort(input);
  }

  async revokeMeshPort(input: Parameters<MeshportRepository['revokeMeshPort']>[0]): Promise<Awaited<ReturnType<MeshportRepository['revokeMeshPort']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.revokeMeshPort(input);
  }
}
