/**
 * RunDensityModel handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: density
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { runDensityModel } from "@denselink/api-server/domains/density/handlers";
import type { DensityDDDDependencies } from "@denselink/api-server/domains/density";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@denselink/tests/shared";
import { DENSITY_USE_CASES } from "../__factories__/use-cases.js";

describe("RunDensityModel", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: DensityDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<DensityDDDDependencies>(
      DENSITY_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeRunDensityModel, "execute").mockResolvedValue(useCaseResult);

    await runDensityModel(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeRunDensityModel.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
