/**
 * In-memory Denselink product domain store (sandbox).
 * Hand-maintained — not regenerated by codegen.
 */

import { randomBytes } from "node:crypto";
import { ulid } from "ulid";

export function nowIso(): string {
  return new Date().toISOString();
}

export function meta(correlationId?: string) {
  return {
    meta: {
      correlationId: correlationId ?? `cor_${ulid().toLowerCase()}`,
      generatedAt: nowIso(),
      requestId: `req_${ulid().toLowerCase()}`,
      timestamp: nowIso(),
    },
  };
}

export function id(prefix: string): string {
  return `${prefix}_${ulid().toLowerCase()}`;
}

export type MeshPortRecord = {
  id: string;
  port: number;
  appId: string;
  sdkVersion?: string;
  status: "allocated" | "revoked";
  collisionBlocked?: boolean;
  conflictingAppId?: string;
  createdAt: string;
  revokedAt?: string;
};

export type LicenseRecord = {
  id: string;
  appId: string;
  developerId: string;
  tier: string;
  status: "active" | "revoked";
  meshPort?: number;
  encryptionAttestation?: boolean;
  attestationStatus?: "pending" | "passed" | "failed";
  buildFingerprint?: string;
  secret?: string;
  createdAt: string;
  revokedAt?: string;
};

export type DensityModelRecord = {
  id: string;
  city: string;
  requiredPenetrationPercent: number;
  estimatedUsefulCoverage: boolean;
  gapBelowThreshold?: boolean;
  estimatedNodes?: number;
  benchmarkNote?: string;
  createdAt: string;
};

export type PiggybackRegion = {
  region: string;
  contributorApps: Array<{
    appId: string;
    densityRank: number;
    activeNodes: number;
    alwaysOnCampaign?: boolean;
  }>;
  launchReadinessScore: number;
  suggestedVenueTypes?: string[];
  greenfield?: boolean;
};

export type VenueProgrammeRecord = {
  id: string;
  venueType: string;
  name: string;
  city?: string;
  activeNodeTarget?: number;
  status: string;
  eventWindowStart?: string;
  eventWindowEnd?: string;
  activeNodes?: number;
  sessionDurationMinutesAvg?: number;
  heatmapBins?: number;
  createdAt: string;
};

export type AlwaysOnCampaignRecord = {
  id: string;
  name: string;
  venueProgrammeId?: string;
  enabled: boolean;
  inflateConsumerMetrics: boolean;
  createdAt: string;
};

export type GrantProgrammeRecord = {
  id: string;
  name: string;
  milestoneMetric: string;
  milestoneThreshold?: number;
  rewardAmount: number;
  status: string;
  densityModelId?: string;
  createdAt: string;
};

export type MilestoneRecord = {
  id: string;
  grantProgrammeId: string;
  appId?: string;
  status: string;
  measuredValue: number;
  reviewedAt?: string;
  disbursedAt?: string;
  createdAt: string;
};

export type TelemetryRecord = {
  id: string;
  appId: string;
  licenseId: string;
  activeNodes: number;
  geoBin?: string;
  sessionDurationMinutesAvg?: number;
  capturedAt: string;
  ingestedAt: string;
};

export const meshPorts = new Map<string, MeshPortRecord>();
export const licenses = new Map<string, LicenseRecord>();
export const densityModels = new Map<string, DensityModelRecord>();
export const venues = new Map<string, VenueProgrammeRecord>();
export const alwaysOnCampaigns = new Map<string, AlwaysOnCampaignRecord>();
export const grants = new Map<string, GrantProgrammeRecord>();
export const milestones = new Map<string, MilestoneRecord>();
export const telemetry = new Map<string, TelemetryRecord>();

let seeded = false;

export function ensureDemoSeed() {
  if (seeded) return;
  seeded = true;
  const now = nowIso();

  const demoApp = "app_01demo00000000000000000001";
  const flareApp = "app_01demo00000000000000000002";

  const mpId = id("mpt");
  meshPorts.set(mpId, {
    id: mpId,
    port: 4242,
    appId: demoApp,
    sdkVersion: "1.0.0",
    status: "allocated",
    createdAt: now,
  });

  const licId = id("lic");
  licenses.set(licId, {
    id: licId,
    appId: demoApp,
    developerId: "dev_01demo00000000000000000001",
    tier: "private_beta",
    status: "active",
    meshPort: 4242,
    encryptionAttestation: false,
    attestationStatus: "pending",
    createdAt: now,
  });

  const denId = id("den");
  densityModels.set(denId, {
    id: denId,
    city: "Dhaka",
    requiredPenetrationPercent: 5,
    estimatedUsefulCoverage: false,
    gapBelowThreshold: true,
    estimatedNodes: 1200,
    benchmarkNote: "Dhaka-class density — useful blanket needs ~5% penetration.",
    createdAt: now,
  });

  const venId = id("ven");
  venues.set(venId, {
    id: venId,
    venueType: "stadium",
    name: "Demo stadium wedge",
    city: "Dhaka",
    activeNodeTarget: 200,
    status: "live",
    activeNodes: 84,
    sessionDurationMinutesAvg: 18,
    heatmapBins: 36,
    createdAt: now,
  });

  const aonId = id("aon");
  alwaysOnCampaigns.set(aonId, {
    id: aonId,
    name: "Flare-class always-on",
    venueProgrammeId: venId,
    enabled: true,
    inflateConsumerMetrics: false,
    createdAt: now,
  });

  const grtId = id("grt");
  grants.set(grtId, {
    id: grtId,
    name: "Density commons grant",
    milestoneMetric: "active_nodes",
    milestoneThreshold: 500,
    rewardAmount: 1000,
    status: "open",
    densityModelId: denId,
    createdAt: now,
  });

  const msnId = id("msn");
  milestones.set(msnId, {
    id: msnId,
    grantProgrammeId: grtId,
    appId: demoApp,
    status: "achieved",
    measuredValue: 520,
    createdAt: now,
  });

  // Keep a second app for piggyback discovery
  void flareApp;
}

export function piggybackSeed(): PiggybackRegion[] {
  ensureDemoSeed();
  return [
    {
      region: "Dhaka",
      contributorApps: [
        {
          appId: "app_01demo00000000000000000001",
          densityRank: 1,
          activeNodes: 420,
          alwaysOnCampaign: false,
        },
        {
          appId: "app_01demo00000000000000000002",
          densityRank: 2,
          activeNodes: 180,
          alwaysOnCampaign: true,
        },
      ],
      launchReadinessScore: 62,
      suggestedVenueTypes: ["stadium", "school"],
      greenfield: false,
    },
    {
      region: "San Francisco",
      contributorApps: [
        {
          appId: "app_01demo00000000000000000001",
          densityRank: 1,
          activeNodes: 2100,
        },
      ],
      launchReadinessScore: 91,
      suggestedVenueTypes: ["mall"],
      greenfield: false,
    },
  ];
}

export function nextPort(): number {
  const used = new Set([...meshPorts.values()].map((p) => p.port));
  let candidate = 4000;
  while (used.has(candidate)) candidate += 1;
  return candidate;
}

export function licenseSecret(): string {
  return `denselink_lic_${randomBytes(16).toString("hex")}`;
}
