/**
 * ListDensityModel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: density
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListDensityModelsParams } from "@denselink/core/density";

export function createListDensityModelRequest(overrides: Partial<ListDensityModelsParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
