/**
 * Telemetry DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Telemetry Domain Module - Composition root
 *
 * DDD: Composition root for telemetry domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AggregateRepositoryAdapter,
} from "@denselink/adapters/telemetry";
import { getIdGeneratorService } from "@denselink/adapters";
import type { AdapterDynamoDBClient } from "@denselink/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteIngestNodeTelemetry,
} from "@denselink/services/telemetry/usecases";
// Ports (interfaces)
import type {
  AggregateRepository,
} from "@denselink/services/telemetry/ports";

export interface TelemetryDomainModule {
  repos: {
    aggregates: AggregateRepository;
  };
  useCases: {
    aggregates: {
      get: ExecuteIngestNodeTelemetry;
    };
  };
}

export function buildTelemetryDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TelemetryDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      aggregates?: AggregateRepository;
    } = {};

    obj.aggregates = new AggregateRepositoryAdapter(dynamoClient);
    return {
      aggregates: obj.aggregates!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    aggregates: {
      get: new ExecuteIngestNodeTelemetry(executionContext, idGenerator, repos.aggregates),
    },
  };
  return { repos, useCases: useCases as TelemetryDomainModule["useCases"] };
}
