"""
API Server Domain Dependencies Generator

Generates platform/api-server domain-dependency wiring from the same domain
discovery as domain-routes. Produces:
- lib/dependencies/domain-dependencies.ts (full file)
- infrastructure/dependency-container.ts (full file)

Both stay in sync with discovered domains (routes/index.ts + *-ddd.dependencies.ts).
"""

from pathlib import Path
from typing import List

from ...base.generator import BaseGenerator, GenerateResult
from ...base.context import GenerationContext
from ...utils.file import ensure_directory, write_file
from ...utils.string import pascal_case, camel_case

from .discovery import discover_api_server_domains


def _js_ident(domain: str) -> str:
    """JS/TS identifier for a domain name (kebab → camelCase)."""
    return camel_case(domain)


def _path_patterns(domains: List[str]) -> List[str]:
    r"""Lines for DOMAIN_PATH_PATTERNS. /auth/ -> identity, then /\/{domain}\// for each."""
    lines = []
    if "identity" in domains:
        lines.append('  { pattern: /\\/auth\\//, domain: "identity" }, // Auth routes belong to identity domain')
    for d in domains:
        lines.append(f'  {{ pattern: /\\/{d}\\//, domain: "{d}" }},')
    return lines


def _domain_imports(domains: List[str]) -> tuple[List[str], List[str]]:
    """Build and type import lines from domains/index.js."""
    build_lines = []
    type_lines = []
    for d in domains:
        pascal = pascal_case(d)
        build_lines.append(f"  build{pascal}DomainModule,")
        type_lines.append(f"  {pascal}DomainModule,")
    return (build_lines, type_lines)


def _switch_cases(domains: List[str]) -> List[str]:
    """Switch case blocks for injectDomainDependencies."""
    return [
        f'      case "{d}":\n        domainDeps = build{pascal_case(d)}DomainModule(dynamoClient);\n        break;'
        for d in domains
    ]


def _domain_deps_interface(domains: List[str]) -> List[str]:
    """DomainDependencies interface entries (quote kebab domain keys for valid TS)."""
    entries = []
    for d in domains:
        key = f'"{d}"' if "-" in d else d
        entries.append(f"  {key}: {pascal_case(d)}DomainModule;")
    return entries


def _getter_functions(domains: List[str]) -> List[str]:
    """getXDeps helper functions."""
    return [
        f'''export function get{pascal_case(d)}Deps(
  request: FastifyRequest,
): DomainDependencies["{d}"] {{
  return getDomainDeps(request, "{d}");
}}'''
        for d in domains
    ]


def _generate_domain_dependencies_ts(domains: List[str], api_server_src: Path) -> str:
    """Full content of domain-dependencies.ts."""
    path_pattern_lines = _path_patterns(domains)
    build_imports, type_imports = _domain_imports(domains)
    switch_cases = _switch_cases(domains)
    interface_entries = _domain_deps_interface(domains)
    getters = _getter_functions(domains)

    return f'''/**
 * Domain Dependency Injection Hook
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Performance-optimized centralized dependency injection that matches domain from path
 * and injects only the needed domain dependencies. Dependencies are cached per domain.
 *
 * Usage:
 * ```typescript
 * fastify.addHook("preHandler", injectDomainDependencies);
 * ```
 *
 * Access dependencies in routes:
 * ```typescript
 * const deps = getDomainDeps(request, "content");
 * ```
 */

import type {{ FastifyRequest, FastifyReply }} from "fastify";
import type {{ AdapterDynamoDBClient }} from "@ddd/adapters";
import {{
  DynamoDBClient,
  BatchWriteItemCommand,
}} from "@aws-sdk/client-dynamodb";
import {{
  DynamoDBDocumentClient,
  QueryCommand,
  GetCommand,
  PutCommand,
  UpdateCommand,
  DeleteCommand,
  ScanCommand,
  TransactWriteCommand,
}} from "@aws-sdk/lib-dynamodb";
import type {{
  QueryCommandInput,
  QueryCommandOutput,
  GetCommandInput,
  GetCommandOutput,
  PutCommandInput,
  PutCommandOutput,
  UpdateCommandInput,
  UpdateCommandOutput,
  DeleteCommandInput,
  DeleteCommandOutput,
  ScanCommandInput,
  ScanCommandOutput,
  TransactWriteCommandInput,
  TransactWriteCommandOutput,
}} from "@aws-sdk/lib-dynamodb";
import type {{
  BatchWriteItemCommandInput,
  BatchWriteItemCommandOutput,
}} from "@aws-sdk/client-dynamodb";
import {{ getAwsCredentialProvider }} from "../infrastructure/aws-credentials.js";

// Import all domain builder functions and types from barrel export
import {{
{chr(10).join(build_imports)}
}} from "../../domains/index.js";
import type {{
{chr(10).join(type_imports)}
}} from "../../domains/index.js";

/**
 * Performance-optimized dependency cache
 */
const dependencyCache = new Map<string, any>();

function getCacheKey(domain: string): string {{
  return domain;
}}

/**
 * Wrapper for DynamoDBDocumentClient that implements AdapterDynamoDBClient interface
 */
class DynamoDBClientAdapter implements AdapterDynamoDBClient {{
  constructor(private readonly docClient: DynamoDBDocumentClient) {{}}

  async query(input: QueryCommandInput): Promise<QueryCommandOutput> {{
    return this.docClient.send(new QueryCommand(input));
  }}

  async get(input: GetCommandInput): Promise<GetCommandOutput> {{
    return this.docClient.send(new GetCommand(input));
  }}

  async put(input: PutCommandInput): Promise<PutCommandOutput> {{
    return this.docClient.send(new PutCommand(input));
  }}

  async update(input: UpdateCommandInput): Promise<UpdateCommandOutput> {{
    return this.docClient.send(new UpdateCommand(input));
  }}

  async delete(input: DeleteCommandInput): Promise<DeleteCommandOutput> {{
    return this.docClient.send(new DeleteCommand(input));
  }}

  async scan(input: ScanCommandInput): Promise<ScanCommandOutput> {{
    return this.docClient.send(new ScanCommand(input));
  }}

  async batchWrite(
    input: BatchWriteItemCommandInput,
  ): Promise<BatchWriteItemCommandOutput> {{
    return this.docClient.send(new BatchWriteItemCommand(input));
  }}

  async transactWrite(
    input: TransactWriteCommandInput,
  ): Promise<TransactWriteCommandOutput> {{
    return this.docClient.send(new TransactWriteCommand(input));
  }}

  async send<T>(command: T): Promise<any> {{
    return this.docClient.send(command as any);
  }}
}}

let dynamoClientInstance: AdapterDynamoDBClient | null = null;

export function getDynamoClientInstance(): AdapterDynamoDBClient {{
  if (!dynamoClientInstance) {{
    const region =
      process.env.AWS_REGION || process.env.AWS_DEFAULT_REGION || "us-east-1";
    const clientConfig: {{
      region: string;
      endpoint?: string;
      credentials?: import("@aws-sdk/types").AwsCredentialIdentityProvider;
    }} = {{ region }};

    const credentialProvider = getAwsCredentialProvider();
    if (credentialProvider) clientConfig.credentials = credentialProvider;

    if (process.env.AWS_ENDPOINT_URL || process.env.LOCALSTACK_ENDPOINT) {{
      clientConfig.endpoint =
        process.env.AWS_ENDPOINT_URL || process.env.LOCALSTACK_ENDPOINT;
    }}

    const client = new DynamoDBClient(clientConfig);
    const docClient = DynamoDBDocumentClient.from(client);
    dynamoClientInstance = new DynamoDBClientAdapter(docClient);
  }}
  return dynamoClientInstance;
}}

/**
 * Domain path patterns - maps URL path segments to domain names
 */
const DOMAIN_PATH_PATTERNS: Array<{{ pattern: RegExp; domain: string }}> = [
{chr(10).join(path_pattern_lines)}
];

function detectDomainFromPath(path: string): string | null {{
  for (const {{ pattern, domain }} of DOMAIN_PATH_PATTERNS) {{
    if (pattern.test(path)) {{
      return domain;
    }}
  }}
  return null;
}}

/**
 * Inject domain dependencies into request object
 */
export async function injectDomainDependencies(
  request: FastifyRequest,
  reply: FastifyReply,
): Promise<void> {{
  const orgId = (request as any).effectiveOrgId;

  if (!orgId) {{
    reply.status(401).send({{
      error: "Unauthorized",
      message:
        "Missing orgId. setOrgContext hook must run before injectDomainDependencies.",
    }});
    return;
  }}

  const path = request.url;
  const domain = detectDomainFromPath(path);

  if (!domain) {{
    return;
  }}

  if (!(request as any).deps) {{
    (request as any).deps = {{}};
  }}

  const cacheKey = getCacheKey(domain);
  let domainDeps = dependencyCache.get(cacheKey);

  if (!domainDeps) {{
    const dynamoClient = getDynamoClientInstance();

    switch (domain) {{
{chr(10).join(switch_cases)}
      default:
        return;
    }}

    dependencyCache.set(cacheKey, domainDeps);
  }}

  (request as any).deps[domain] = domainDeps;
}}

/**
 * Type-safe helper to get domain dependencies from request
 */
export function getDomainDeps<T extends keyof DomainDependencies>(
  request: FastifyRequest,
  domain: T,
): DomainDependencies[T] {{
  const deps = (request as any).deps;
  if (!deps || !deps[domain]) {{
    throw new Error(
      `${{domain}} dependencies not found. Ensure injectDomainDependencies hook ran and path matches ${{domain}} domain.`,
    );
  }}
  return deps[domain];
}}

/**
 * Type definitions for domain dependencies
 */
export interface DomainDependencies {{
{chr(10).join(interface_entries)}
}}

export function clearDomainDependencyCache(domain: string): void {{
  const cacheKey = getCacheKey(domain);
  dependencyCache.delete(cacheKey);
}}

export function clearAllDomainDependencyCaches(): void {{
  dependencyCache.clear();
}}

/**
 * Convenience helpers for each domain (type-safe)
 */
{chr(10).join(getters)}
'''


def _generate_dependency_container_ts(domains: List[str], api_server_src: Path) -> str:
    """Full content of dependency-container.ts."""
    build_imports, type_imports = _domain_imports(domains)

    cache_decls = "\n".join(
        f"  private {_js_ident(d)}Module: {pascal_case(d)}DomainModule | null = null;"
        for d in domains
    )

    # get/clear/getForRequest blocks; planning uses getSchedulingDependencies alias
    get_blocks = []
    clear_blocks = []
    for_request_blocks = []
    for d in domains:
        p = pascal_case(d)
        ident = _js_ident(d)
        getter_name = "getSchedulingDependencies" if d == "planning" else f"get{p}Dependencies"
        if d == "planning":
            get_blocks.append(f'''
  /**
   * Get planning domain module
   */
  getSchedulingDependencies(): {p}DomainModule {{
    if (!this.{ident}Module) {{
      this.{ident}Module = build{p}DomainModule(this.dynamoClient);
    }}
    return this.{ident}Module;
  }}''')
        else:
            get_blocks.append(f'''
  /**
   * Get {d} domain module
   */
  {getter_name}(): {p}DomainModule {{
    if (!this.{ident}Module) {{
      this.{ident}Module = build{p}DomainModule(this.dynamoClient);
    }}
    return this.{ident}Module;
  }}''')
        if d == "planning":
            clear_blocks.append(f"  clearSchedulingDependencies(): void {{ this.{ident}Module = null; }}")
        elif d == "social":
            clear_blocks.append(f"  clearSocialDependencies(): void {{ this.{ident}Module = null; }}")
        else:
            clear_blocks.append(f"  clear{p}Dependencies(): void {{ this.{ident}Module = null; }}")
        for_req_name = "getSchedulingDependenciesForRequest" if d == "planning" else f"get{p}DependenciesForRequest"
        for_request_blocks.append(f'''
  {for_req_name}(): {p}DomainModule {{
    return this.{getter_name}();
  }}''')

    # Social alias: getChannelDependencies = getSocialDependencies
    social_get = ""
    if "social" in domains:
        social_get = '''
  /**
   * Get social/channel domain module
   */
  getChannelDependencies(): SocialDomainModule {
    return this.getSocialDependencies();
  }

  clearChannelDependencies(): void {
    this.socialModule = null;
  }
'''
    clear_all_lines = [f"    this.{_js_ident(d)}Module = null;" for d in domains]

    return f'''/**
 * Dependency Container
 *
 * AUTO-GENERATED by codegen (api_server_domain_dependencies). Do not edit by hand.
 * Regenerate with: pnpm run codegen (domain list from platform/api-server/src/domains rescan).
 *
 * Manages dependency creation and caching per domain.
 */

import type {{ AdapterDynamoDBClient }} from "@ddd/adapters";
import {{ getDynamoClientInstance }} from "../lib/dependencies/domain-dependencies.js";
import {{ executionContextService }} from "../lib/context/execution-context.service.js";
import {{
{chr(10).join(build_imports)}
}} from "../domains/index.js";
import type {{
{chr(10).join(type_imports)}
}} from "../domains/index.js";

class DependencyContainer {{
  private readonly dynamoClient: AdapterDynamoDBClient;

{cache_decls}

  constructor(dynamoClient: AdapterDynamoDBClient) {{
    this.dynamoClient = dynamoClient;
  }}
{chr(10).join(get_blocks)}
{social_get}
{chr(10).join(clear_blocks)}
{chr(10).join(for_request_blocks)}

  /**
   * Clear all caches
   */
  clearAllCaches(): void {{
{chr(10).join(clear_all_lines)}
  }}
}}

let dependencyContainerInstance: DependencyContainer | null = null;

export function getDependencyContainer(): DependencyContainer {{
  if (!dependencyContainerInstance) {{
    const dynamoClient = getDynamoClientInstance();
    dependencyContainerInstance = new DependencyContainer(dynamoClient);
  }}
  return dependencyContainerInstance;
}}
'''


class ApiServerDomainDependenciesGenerator(BaseGenerator):
    """Generates api-server domain-dependencies.ts and dependency-container.ts from discovered domains."""

    @property
    def name(self) -> str:
        return "API Server Domain Dependencies Generator"

    @property
    def version(self) -> str:
        return "1.0.0"

    @property
    def type(self) -> str:
        return "api_server_domain_dependencies"

    def generate(self, context: GenerationContext) -> GenerateResult:
        files: List[Path] = []
        warnings: List[str] = []

        project_root = context.config.paths.project_root
        api_server_src = project_root / "platform" / "api-server" / "src"
        domains_dir = api_server_src / "domains"

        domains = discover_api_server_domains(domains_dir)
        if not domains:
            context.logger.warn(
                "No api-server domains found; skipping domain-dependencies and dependency-container"
            )
            return GenerateResult(files=files, warnings=warnings)

        # domain-dependencies.ts
        deps_dir = api_server_src / "lib" / "dependencies"
        ensure_directory(deps_dir)
        domain_deps_file = deps_dir / "domain-dependencies.ts"
        write_file(domain_deps_file, _generate_domain_dependencies_ts(domains, api_server_src))
        files.append(domain_deps_file)

        # dependency-container.ts
        infra_dir = api_server_src / "infrastructure"
        ensure_directory(infra_dir)
        container_file = infra_dir / "dependency-container.ts"
        write_file(container_file, _generate_dependency_container_ts(domains, api_server_src))
        files.append(container_file)

        context.logger.info(
            f"Generated api-server domain-dependencies and dependency-container with {len(domains)} domains"
        )
        return GenerateResult(files=files, warnings=warnings)
