/**
 * ListVenue DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { ListVenueProgrammesParams } from "@denselink/core/venues";

export function createListVenueRequest(overrides: Partial<ListVenueProgrammesParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
