/**
 * GetLicense DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetLicenseKeyParams } from "@denselink/core/licenses";

export function createGetLicenseRequest(overrides: Partial<GetLicenseKeyParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
