/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: meshports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./allocate-mesh-port.handler.test.js";
export * from "./get-mesh-port.handler.test.js";
export * from "./list-mesh-ports.handler.test.js";
export * from "./revoke-mesh-port.handler.test.js";
