/**
 * ListMeshPorts handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: meshports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listMeshPorts } from "@denselink/api-server/domains/meshports/handlers";
import type { MeshportsDDDDependencies } from "@denselink/api-server/domains/meshports";
import { createMeshport as createMeshportEntity } from "@denselink/factories/meshports";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@denselink/tests/shared";
import { MESHPORTS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListMeshPorts", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: MeshportsDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<MeshportsDDDDependencies>(
      MESHPORTS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createMeshportEntity({ orgId }),
      createMeshportEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListMeshPorts, "execute").mockResolvedValue(useCaseResult);

    await listMeshPorts(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListMeshPorts.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
