/**
 * ExecuteCreateGrantProgramme - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateGrantProgramme Use Case
 *
 * DDD: Application use case for create Grant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateGrantProgrammeInput, CreateGrantProgrammeOutput } from "../dto/grant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { GrantRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateGrantProgramme {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly grant: GrantRepository
  ) {}

  async execute(input: CreateGrantProgrammeInput): Promise<CreateGrantProgrammeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grtId();

    // All field names extracted from OpenAPI spec: densityModelId, milestoneMetric, milestoneThreshold, name, rewardAmount
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }
    if (!input.milestoneMetric) {
      throw new ValidationError("milestoneMetric is required");
    }
    if (!input.rewardAmount) {
      throw new ValidationError("rewardAmount is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (grants domain)
    const entityId = this.idGenerator.grtId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.grant.createGrantProgramme({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateGrantProgrammeOutput;
  }
}
