/**
 * ExecuteDisburseMilestone - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteDisburseMilestone Use Case
 *
 * DDD: Application use case for get Disburse.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { DisburseMilestoneInput, DisburseMilestoneOutput } from "../dto/disburse.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { DisburseRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteDisburseMilestone {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly disburse: DisburseRepository
  ) {}

  async execute(input: DisburseMilestoneInput): Promise<DisburseMilestoneOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grtId();

    // All field names extracted from OpenAPI spec: note
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).milestoneId) {
      throw new ValidationError("milestoneId is required");
    }
    const milestoneId = (input as any).milestoneId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.disburse.disburseMilestone({ milestoneId: milestoneId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${milestoneId}`);
    }

    return entity as DisburseMilestoneOutput;
  }
}
