/**
 * ExecuteGetGrantProgramme - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetGrantProgramme Use Case
 *
 * DDD: Application use case for get Grant.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetGrantProgrammeInput, GetGrantProgrammeOutput } from "../dto/grant.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { GrantRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetGrantProgramme {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly grant: GrantRepository
  ) {}

  async execute(input: GetGrantProgrammeInput): Promise<GetGrantProgrammeOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.grtId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).grantProgrammeId) {
      throw new ValidationError("grantProgrammeId is required");
    }
    const grantprogrammeId = (input as any).grantProgrammeId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.grant.getGrantProgramme({ grantProgrammeId: grantprogrammeId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${grantprogrammeId}`);
    }

    return entity as GetGrantProgrammeOutput;
  }
}
