/**
 * AlwaysOnCampaign Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { AlwaysOnCampaignEntity } from "@denselink/core/venues/models/index.js";
import { venuesSchemas } from "@denselink/core/venues";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ven";

export function createAlwaysOnCampaign(overrides: Partial<AlwaysOnCampaignEntity> = {}) {
  const raw = {
    id: overrides.id ?? `aon_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    enabled: overrides.enabled ?? faker.datatype.boolean(),
    name: overrides.name ?? faker.person.fullName(),
    ...overrides,
  };

  return venuesSchemas.AlwaysOnCampaign.parse(raw);
}

export function alwaysOnCampaignBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createAlwaysOnCampaign(overrides));
}
