/**
 * Milestone Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/grants.openapi.types.js";
import { schemas } from "../schemas/grants.schemas.js";

/**
 * Entity: MilestoneEntity
 * Description: Represents the Milestone domain model.
 * Source: schemas.Milestone
 * Type: Domain Entity (API)
 */
export const MilestoneEntitySchema = schemas.Milestone;
export type MilestoneEntity = components["schemas"]["Milestone"];
