/**
 * AggregateRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: telemetry
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AggregateRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AggregateRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AggregateRepository,
} from "@denselink/services/telemetry";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AggregateRepositoryDdb } from "./aggregate-repository.ddb.js";

/**
 * AggregateRepositoryAdapter
 *
 * Implements AggregateRepository port for infrastructure layer.
 */
export class AggregateRepositoryAdapter implements AggregateRepository {
  private readonly ddb: AggregateRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AggregateRepositoryDdb(this.dynamoClient);
  }

  async ingestNodeTelemetry(input: Parameters<AggregateRepository['ingestNodeTelemetry']>[0]): Promise<Awaited<ReturnType<AggregateRepository['ingestNodeTelemetry']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.ingestNodeTelemetry(input);
  }
}
