/**
 * Grants DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Grants Domain Module - Composition root
 *
 * DDD: Composition root for grants domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  DisburseRepositoryAdapter,
  GrantRepositoryAdapter,
  MilestoneRepositoryAdapter,
} from "@denselink/adapters/grants";
import { getIdGeneratorService } from "@denselink/adapters";
import type { AdapterDynamoDBClient } from "@denselink/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateGrantProgramme,
  ExecuteDisburseMilestone,
  ExecuteGetGrantProgramme,
  ExecuteListGrantMilestones,
  ExecuteListGrantProgrammes,
} from "@denselink/services/grants/usecases";
// Ports (interfaces)
import type {
  DisburseRepository,
  GrantRepository,
  MilestoneRepository,
} from "@denselink/services/grants/ports";

export interface GrantsDomainModule {
  repos: {
    disburses: DisburseRepository;
    grants: GrantRepository;
    milestones: MilestoneRepository;
  };
  useCases: {
    disburses: {
      get: ExecuteDisburseMilestone;
    };
    grants: {
      create: ExecuteCreateGrantProgramme;
      get: ExecuteGetGrantProgramme;
      list: ExecuteListGrantProgrammes;
    };
    milestones: {
      list: ExecuteListGrantMilestones;
    };
  };
}

export function buildGrantsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GrantsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      disburses?: DisburseRepository;
      grants?: GrantRepository;
      milestones?: MilestoneRepository;
    } = {};

    obj.disburses = new DisburseRepositoryAdapter(dynamoClient);
    obj.grants = new GrantRepositoryAdapter(dynamoClient);
    obj.milestones = new MilestoneRepositoryAdapter(dynamoClient);
    return {
      disburses: obj.disburses!,
      grants: obj.grants!,
      milestones: obj.milestones!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    disburses: {
      get: new ExecuteDisburseMilestone(executionContext, idGenerator, repos.disburses),
    },
    grants: {
      create: new ExecuteCreateGrantProgramme(executionContext, idGenerator, repos.grants),
      get: new ExecuteGetGrantProgramme(executionContext, idGenerator, repos.grants),
      list: new ExecuteListGrantProgrammes(executionContext, idGenerator, repos.grants),
    },
    milestones: {
      list: new ExecuteListGrantMilestones(executionContext, idGenerator, repos.milestones),
    },
  };
  return { repos, useCases: useCases as GrantsDomainModule["useCases"] };
}
