/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { attestationRoutes } from "./attestation.routes.js";
export { licenseRoutes } from "./license.routes.js";
export { revokeRoutes } from "./revoke.routes.js";
