/**
 * LicenseRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LicenseRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LicenseRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LicenseRepository,
} from "@denselink/services/licenses";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LicenseRepositoryDdb } from "./license-repository.ddb.js";

/**
 * LicenseRepositoryAdapter
 *
 * Implements LicenseRepository port for infrastructure layer.
 */
export class LicenseRepositoryAdapter implements LicenseRepository {
  private readonly ddb: LicenseRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LicenseRepositoryDdb(this.dynamoClient);
  }

  async listLicenseKeys(input: Parameters<LicenseRepository['listLicenseKeys']>[0]): Promise<Awaited<ReturnType<LicenseRepository['listLicenseKeys']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLicenseKeys(input);
  }

  async issueLicenseKey(input: Parameters<LicenseRepository['issueLicenseKey']>[0]): Promise<Awaited<ReturnType<LicenseRepository['issueLicenseKey']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.issueLicenseKey(input);
  }

  async getLicenseKey(input: Parameters<LicenseRepository['getLicenseKey']>[0]): Promise<Awaited<ReturnType<LicenseRepository['getLicenseKey']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLicenseKey(input);
  }
}
