/**
 * LicenseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LicenseRepository Port
 *
 * DDD: Application port for licenserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLicenseKeyInput, GetLicenseKeyOutput, IssueLicenseKeyInput, IssueLicenseKeyOutput, ListLicenseKeysInput, ListLicenseKeysOutput } from "../dto/license.dto";
export interface LicenseRepository {
  listLicenseKeys(input: ListLicenseKeysInput): Promise<ListLicenseKeysOutput>;
  issueLicenseKey(input: IssueLicenseKeyInput): Promise<IssueLicenseKeyOutput>;
  getLicenseKey(input: GetLicenseKeyInput): Promise<GetLicenseKeyOutput>;
}

export type { GetLicenseKeyInput, GetLicenseKeyOutput, IssueLicenseKeyInput, IssueLicenseKeyOutput, ListLicenseKeysInput, ListLicenseKeysOutput } from "../dto/license.dto";
