/**
 * Milestone DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Milestone DTOs
 *
 * DDD: Application DTOs for Milestone use cases.
 */

import type { ListGrantMilestonesParams } from "@denselink/core/grants/types";

export type ListGrantMilestonesInput = ListGrantMilestonesParams;

export type ListGrantMilestonesOutput = {};
