/**
 * ExecuteListDensityModels - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: density
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDensityModels Use Case
 *
 * DDD: Application use case for list DensityModel.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDensityModelsInput, ListDensityModelsOutput } from "../dto/density-model.dto";
import type { ExecutionContextService, IdGeneratorService } from "@denselink/services/_shared/index.js";
import type { DensityModelRepository } from "../ports";

export class ExecuteListDensityModels {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly densityModel: DensityModelRepository
  ) {}

  async execute(input: ListDensityModelsInput): Promise<ListDensityModelsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.denId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.densityModel.listDensityModels({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDensityModelsOutput;
  }
}
