/**
 * Venues DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Venues Domain Module - Composition root
 *
 * DDD: Composition root for venues domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AlwaysOnCampaignRepositoryAdapter,
  VenueRepositoryAdapter,
} from "@denselink/adapters/venues";
import { getIdGeneratorService } from "@denselink/adapters";
import type { AdapterDynamoDBClient } from "@denselink/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateAlwaysOnCampaign,
  ExecuteCreateVenueProgramme,
  ExecuteGetVenueProgramme,
  ExecuteListAlwaysOnCampaigns,
  ExecuteListVenueProgrammes,
} from "@denselink/services/venues/usecases";
// Ports (interfaces)
import type {
  AlwaysOnCampaignRepository,
  VenueRepository,
} from "@denselink/services/venues/ports";

export interface VenuesDomainModule {
  repos: {
    alwaysOnCampaigns: AlwaysOnCampaignRepository;
    venues: VenueRepository;
  };
  useCases: {
    alwaysOnCampaigns: {
      create: ExecuteCreateAlwaysOnCampaign;
      list: ExecuteListAlwaysOnCampaigns;
    };
    venues: {
      create: ExecuteCreateVenueProgramme;
      get: ExecuteGetVenueProgramme;
      list: ExecuteListVenueProgrammes;
    };
  };
}

export function buildVenuesDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): VenuesDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      alwaysOnCampaigns?: AlwaysOnCampaignRepository;
      venues?: VenueRepository;
    } = {};

    obj.alwaysOnCampaigns = new AlwaysOnCampaignRepositoryAdapter(dynamoClient);
    obj.venues = new VenueRepositoryAdapter(dynamoClient);
    return {
      alwaysOnCampaigns: obj.alwaysOnCampaigns!,
      venues: obj.venues!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    alwaysOnCampaigns: {
      create: new ExecuteCreateAlwaysOnCampaign(executionContext, idGenerator, repos.alwaysOnCampaigns),
      list: new ExecuteListAlwaysOnCampaigns(executionContext, idGenerator, repos.alwaysOnCampaigns),
    },
    venues: {
      create: new ExecuteCreateVenueProgramme(executionContext, idGenerator, repos.venues),
      get: new ExecuteGetVenueProgramme(executionContext, idGenerator, repos.venues),
      list: new ExecuteListVenueProgrammes(executionContext, idGenerator, repos.venues),
    },
  };
  return { repos, useCases: useCases as VenuesDomainModule["useCases"] };
}
