/**
 * Handlers for DensityModel
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: density
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DensityDomainModule } from "../dependencies/density-ddd.dependencies.js";
import type { GetDensityModelInput, ListDensityModelsInput, RunDensityModelInput } from "@denselink/services/density";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/density-models
 * Operation: listDensityModels
 */
export async function listDensityModels(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DensityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDensityModelsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.models.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/density-models
 * Operation: runDensityModel
 */
export async function runDensityModel(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: DensityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: RunDensityModelInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.models.create.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/density-models/{densityModelId}
 * Operation: getDensityModel
 */
export async function getDensityModel(
  request: FastifyRequest<{ Params: { densityModelId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: DensityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDensityModelInput = {
    densityModelId: request.params.densityModelId,
  };
  const result = await deps.useCases.models.get.execute(input);
  return reply.code(200).send(result);
}


