/**
 * Handlers for Piggyback
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: density
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { DensityDomainModule } from "../dependencies/density-ddd.dependencies.js";
import type { ListPiggybackRegionsInput } from "@denselink/services/density";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/piggyback
 * Operation: listPiggybackRegions
 */
export async function listPiggybackRegions(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[], region?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: DensityDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListPiggybackRegionsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.piggybacks.list.execute(input);
  return reply.code(200).send(result);
}


