/**
 * Handlers for Attestation
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { LicensesDomainModule } from "../dependencies/licenses-ddd.dependencies.js";
import type { BindLicenseAttestationInput } from "@denselink/services/licenses";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/licenses/{licenseId}/attestation
 * Operation: bindLicenseAttestation
 */
export async function bindLicenseAttestation(
  request: FastifyRequest<{ Params: { licenseId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: LicensesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: BindLicenseAttestationInput = {
    licenseId: request.params.licenseId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.attestations.get.execute(input);
  return reply.code(200).send(result);
}


