/**
 * Handlers for AlwaysOnCampaign
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { VenuesDomainModule } from "../dependencies/venues-ddd.dependencies.js";
import type { CreateAlwaysOnCampaignInput, ListAlwaysOnCampaignsInput } from "@denselink/services/venues";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/always-on-campaigns
 * Operation: listAlwaysOnCampaigns
 */
export async function listAlwaysOnCampaigns(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: VenuesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAlwaysOnCampaignsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.alwaysOnCampaigns.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/always-on-campaigns
 * Operation: createAlwaysOnCampaign
 */
export async function createAlwaysOnCampaign(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: VenuesDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateAlwaysOnCampaignInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.alwaysOnCampaigns.create.execute(input);
  return reply.code(201).send(result);
}


