/**
 * Attestation DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Attestation DTOs
 *
 * DDD: Application DTOs for Attestation use cases.
 */

import type { BindLicenseAttestationParams, BindLicenseAttestationRequestInput } from "@denselink/core/licenses/types";

export type BindLicenseAttestationInput = BindLicenseAttestationParams & BindLicenseAttestationRequestInput;

export type BindLicenseAttestationOutput = {};
