/**
 * License DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * License DTOs
 *
 * DDD: Application DTOs for License use cases.
 */

import type { GetLicenseKeyParams, IssueLicenseKeyRequestInput, ListLicenseKeysParams } from "@denselink/core/licenses/types";

export type ListLicenseKeysInput = ListLicenseKeysParams;

export type IssueLicenseKeyInput = IssueLicenseKeyRequestInput;

export type GetLicenseKeyInput = GetLicenseKeyParams;

export type ListLicenseKeysOutput = {};

export type IssueLicenseKeyOutput = {};

export type GetLicenseKeyOutput = {};
