/**
 * Revoke DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Revoke DTOs
 *
 * DDD: Application DTOs for Revoke use cases.
 */

import type { RevokeLicenseKeyParams } from "@denselink/core/licenses/types";

export type RevokeLicenseKeyInput = RevokeLicenseKeyParams;

export type RevokeLicenseKeyOutput = {};
