/**
 * Repository interface for Milestone
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  MilestoneEntity
} from "../models/milestone.entity.js";
import type {
  ListGrantMilestonesParams
} from "../types/index.js";
/**
 * MilestoneRepository Interface
 */
export interface MilestoneRepository extends ReadRepository<MilestoneEntity, string, ListGrantMilestonesParams> {

}
