/**
 * DisburseRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DisburseRepository Port
 *
 * DDD: Application port for disburserepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { DisburseMilestoneInput, DisburseMilestoneOutput } from "../dto/disburse.dto";
export interface DisburseRepository {
  disburseMilestone(input: DisburseMilestoneInput): Promise<DisburseMilestoneOutput>;
}

export type { DisburseMilestoneInput, DisburseMilestoneOutput } from "../dto/disburse.dto";
