/**
 * GrantRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * GrantRepository Port
 *
 * DDD: Application port for grantrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateGrantProgrammeInput, CreateGrantProgrammeOutput, GetGrantProgrammeInput, GetGrantProgrammeOutput, ListGrantProgrammesInput, ListGrantProgrammesOutput } from "../dto/grant.dto";
export interface GrantRepository {
  listGrantProgrammes(input: ListGrantProgrammesInput): Promise<ListGrantProgrammesOutput>;
  createGrantProgramme(input: CreateGrantProgrammeInput): Promise<CreateGrantProgrammeOutput>;
  getGrantProgramme(input: GetGrantProgrammeInput): Promise<GetGrantProgrammeOutput>;
}

export type { CreateGrantProgrammeInput, CreateGrantProgrammeOutput, GetGrantProgrammeInput, GetGrantProgrammeOutput, ListGrantProgrammesInput, ListGrantProgrammesOutput } from "../dto/grant.dto";
