/**
 * MilestoneRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MilestoneRepository Port
 *
 * DDD: Application port for milestonerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListGrantMilestonesInput, ListGrantMilestonesOutput } from "../dto/milestone.dto";
export interface MilestoneRepository {
  listGrantMilestones(input: ListGrantMilestonesInput): Promise<ListGrantMilestonesOutput>;
}

export type { ListGrantMilestonesInput, ListGrantMilestonesOutput } from "../dto/milestone.dto";
