/**
 * Routes for Grant
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createGrantProgramme, getGrantProgramme, listGrantProgrammes } from "../handlers/grant.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function grantRoutes(fastify: FastifyInstance) {
  // POST /v1/grants (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/grants",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGrantsDependenciesForRequest();
        await createGrantProgramme(request, reply, deps);
      });
    }
  );


  // GET /v1/grants (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/grants",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGrantsDependenciesForRequest();
        await listGrantProgrammes(request, reply, deps);
      });
    }
  );


  // GET /v1/grants/{grantProgrammeId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/grants/:grantProgrammeId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { grantProgrammeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGrantsDependenciesForRequest();
        await getGrantProgramme(request, reply, deps);
      });
    }
  );


}
