/**
 * Routes for Milestone
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { listGrantMilestones } from "../handlers/milestone.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function milestoneRoutes(fastify: FastifyInstance) {
  // GET /v1/grants/{grantProgrammeId}/milestones (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/grants/:grantProgrammeId/milestones",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { grantProgrammeId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGrantsDependenciesForRequest();
        await listGrantMilestones(request, reply, deps);
      });
    }
  );


}
