/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Grants Domain Use Cases
 * 
 * List of all use case names for the grants domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const GRANTS_USE_CASES = [
  "executeCreateGrantProgramme",
  "executeDisburseMilestone",
  "executeGetGrantProgramme",
  "executeListGrantMilestones",
  "executeListGrantProgrammes"
] as const;
