/**
 * BetaCohortRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * BetaCohortRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements BetaCohortRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  BetaCohortRepository,
} from "@denselink/services/reports";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { BetaCohortRepositoryDdb } from "./beta-cohort-repository.ddb.js";

/**
 * BetaCohortRepositoryAdapter
 *
 * Implements BetaCohortRepository port for infrastructure layer.
 */
export class BetaCohortRepositoryAdapter implements BetaCohortRepository {
  private readonly ddb: BetaCohortRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new BetaCohortRepositoryDdb(this.dynamoClient);
  }

  async getBetaCohort(input: Parameters<BetaCohortRepository['getBetaCohort']>[0]): Promise<Awaited<ReturnType<BetaCohortRepository['getBetaCohort']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getBetaCohort(input);
  }
}
