/**
 * ContributionRankRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ContributionRankRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ContributionRankRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ContributionRankRepository,
} from "@denselink/services/reports";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ContributionRankRepositoryDdb } from "./contribution-rank-repository.ddb.js";

/**
 * ContributionRankRepositoryAdapter
 *
 * Implements ContributionRankRepository port for infrastructure layer.
 */
export class ContributionRankRepositoryAdapter implements ContributionRankRepository {
  private readonly ddb: ContributionRankRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ContributionRankRepositoryDdb(this.dynamoClient);
  }

  async getContributionRank(input: Parameters<ContributionRankRepository['getContributionRank']>[0]): Promise<Awaited<ReturnType<ContributionRankRepository['getContributionRank']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getContributionRank(input);
  }
}
