/**
 * DensityRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DensityRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DensityRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DensityRepository,
} from "@denselink/services/reports";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DensityRepositoryDdb } from "./density-repository.ddb.js";

/**
 * DensityRepositoryAdapter
 *
 * Implements DensityRepository port for infrastructure layer.
 */
export class DensityRepositoryAdapter implements DensityRepository {
  private readonly ddb: DensityRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DensityRepositoryDdb(this.dynamoClient);
  }

  async getDensityReport(input: Parameters<DensityRepository['getDensityReport']>[0]): Promise<Awaited<ReturnType<DensityRepository['getDensityReport']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDensityReport(input);
  }
}
