/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: reports
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./beta-cohort-repository.ddb.js";
export * from "./contribution-rank-repository.ddb.js";
export * from "./density-repository.ddb.js";
export * from "./sponsor-roi-repository.ddb.js";
export * from "./beta-cohort-repository.adapter.js";
export * from "./contribution-rank-repository.adapter.js";
export * from "./density-repository.adapter.js";
export * from "./sponsor-roi-repository.adapter.js";
