/**
 * AlwaysOnCampaign DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AlwaysOnCampaign DTOs
 *
 * DDD: Application DTOs for AlwaysOnCampaign use cases.
 */

import type { CreateAlwaysOnCampaignRequestInput, ListAlwaysOnCampaignsParams } from "@denselink/core/venues/types";

export type ListAlwaysOnCampaignsInput = ListAlwaysOnCampaignsParams;

export type CreateAlwaysOnCampaignInput = CreateAlwaysOnCampaignRequestInput;

export type ListAlwaysOnCampaignsOutput = {};

export type CreateAlwaysOnCampaignOutput = {};
