/**
 * Venue DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Venue DTOs
 *
 * DDD: Application DTOs for Venue use cases.
 */

import type { CreateVenueProgrammeRequestInput, GetVenueProgrammeParams, ListVenueProgrammesParams } from "@denselink/core/venues/types";

export type ListVenueProgrammesInput = ListVenueProgrammesParams;

export type CreateVenueProgrammeInput = CreateVenueProgrammeRequestInput;

export type GetVenueProgrammeInput = GetVenueProgrammeParams;

export type ListVenueProgrammesOutput = {};

export type CreateVenueProgrammeOutput = {};

export type GetVenueProgrammeOutput = {};
