/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: licenses
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Licenses Domain Use Cases
 * 
 * List of all use case names for the licenses domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const LICENSES_USE_CASES = [
  "executeBindLicenseAttestation",
  "executeGetLicenseKey",
  "executeIssueLicenseKey",
  "executeListLicenseKeys",
  "executeRevokeLicenseKey"
] as const;
