/**
 * Milestone Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: grants
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { MilestoneEntity } from "@denselink/core/grants/models/index.js";
import { grantsSchemas } from "@denselink/core/grants";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "grt";

export function createMilestone(overrides: Partial<MilestoneEntity> = {}) {
  const raw = {
    id: overrides.id ?? `msn_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    grantProgrammeId: overrides.grantProgrammeId ?? `grt_${ulid().toLowerCase()}`,
    measuredValue: overrides.measuredValue ?? faker.number.int(),
    status: overrides.status ?? "pending",
    ...overrides,
  };

  return grantsSchemas.Milestone.parse(raw);
}

export function milestoneBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createMilestone(overrides));
}
