/**
 * GetVenueProgramme handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getVenueProgramme } from "@denselink/api-server/domains/venues/handlers";
import type { VenuesDDDDependencies } from "@denselink/api-server/domains/venues";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@denselink/tests/shared";
import { VENUES_USE_CASES } from "../__factories__/use-cases.js";

describe("GetVenueProgramme", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: VenuesDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<VenuesDDDDependencies>(
      VENUES_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetVenueProgramme, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { venueProgrammeId: entity.id };

    await getVenueProgramme(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetVenueProgramme.execute).toHaveBeenCalledWith(expect.objectContaining({ venueProgrammeId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { venueProgrammeId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetVenueProgramme, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getVenueProgramme(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
