"""
Builder Protocol and Base Class - Standardized builder pattern
"""

from typing import Protocol, Optional
from zero_codegen.base.context import GenerationContext


class Builder(Protocol):
    """Protocol for all builders - defines the contract builders must follow"""

    def build(self, context: GenerationContext, **kwargs) -> str:
        """
        Build content from context.

        Args:
            context: Generation context
            **kwargs: Additional builder-specific arguments

        Returns:
            Generated content as string
        """
        ...


class BaseBuilder:
    """Base class for builders with common utilities"""

    @staticmethod
    def generate_header(
        context: GenerationContext,
        description: str,
        generator_name: Optional[str] = None,
        version: Optional[str] = None,
    ) -> str:
        """
        Generate a standard file header comment.

        Args:
            context: Generation context
            description: Description for the header
            generator_name: Optional generator name (uses context if not provided)
            version: Optional version (uses context config version if not provided)

        Returns:
            Header comment string
        """
        generator = generator_name or "Builder"
        ver = version or context.config.version or "1.0.0"

        return f"""/**
 * {description}
 *
 * Generated by {generator} v{ver}
 * Domain: {context.domain_name}
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

"""
