"""
Base generator class for unified codegen
"""

from abc import ABC, abstractmethod
from typing import Optional
from pathlib import Path

from .context import GenerationContext
from .errors import GenerationError


class GenerateResult:
    """Result of code generation"""
    def __init__(
        self,
        files: Optional[list[Path]] = None,
        warnings: Optional[list[str]] = None,
        errors: Optional[list[str]] = None
    ):
        self.files = files or []
        self.warnings = warnings or []
        self.errors = errors or []
    
    @property
    def success(self) -> bool:
        """Check if generation was successful"""
        return len(self.errors) == 0


class BaseGenerator(ABC):
    """Base class for all generators"""
    
    @property
    @abstractmethod
    def name(self) -> str:
        """Generator name"""
        pass
    
    @property
    @abstractmethod
    def version(self) -> str:
        """Generator version"""
        pass
    
    @property
    @abstractmethod
    def type(self) -> str:
        """Generator type identifier"""
        pass
    
    @abstractmethod
    def generate(self, context: GenerationContext) -> GenerateResult:
        """Generate code"""
        pass
    
    def validate_context(self, context: GenerationContext) -> None:
        """Validate generation context"""
        if not context.spec:
            raise GenerationError(f"OpenAPI spec is required for {self.name}")
        if not context.domain_name:
            raise GenerationError(f"Domain name is required for {self.name}")
    
    def generate_header(
        self,
        context: GenerationContext,
        description: str,
        generator_name: Optional[str] = None,
        use_auto_generated_format: bool = False,
    ) -> str:
        """Generate file header comment"""
        generator = generator_name or self.name
        version = context.config.version if hasattr(context.config, 'version') else self.version
        
        # Get bundled spec path for source reference
        source_path = ""
        if hasattr(context, 'bundled_path') and context.bundled_path:
            source_path = f"\n * Source: {context.bundled_path}"
        
        if use_auto_generated_format:
            return f"""/**
 * AUTO-GENERATED CODE — DO NOT EDIT
 *
 * Generator: {generator} v{version}{source_path}
 */

"""
        else:
            return f"""/**
 * {description}
 *
 * Generated by {generator} v{self.version}
 * Generator Version: {version}
 * Domain: {context.domain_name}
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

"""
