/**
 * VenueRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: venues
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * VenueRepository Port
 *
 * DDD: Application port for venuerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateVenueProgrammeInput, CreateVenueProgrammeOutput, GetVenueProgrammeInput, GetVenueProgrammeOutput, ListVenueProgrammesInput, ListVenueProgrammesOutput } from "../dto/venue.dto";
export interface VenueRepository {
  listVenueProgrammes(input: ListVenueProgrammesInput): Promise<ListVenueProgrammesOutput>;
  createVenueProgramme(input: CreateVenueProgrammeInput): Promise<CreateVenueProgrammeOutput>;
  getVenueProgramme(input: GetVenueProgrammeInput): Promise<GetVenueProgrammeOutput>;
}

export type { CreateVenueProgrammeInput, CreateVenueProgrammeOutput, GetVenueProgrammeInput, GetVenueProgrammeOutput, ListVenueProgrammesInput, ListVenueProgrammesOutput } from "../dto/venue.dto";
